# -*- coding: utf-8 -*-
"""Skin_Cancer_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13VZwOAUAxkHCRxEKJPFBDjU4-3Ebl7yi
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from scipy import stats

warnings.filterwarnings("ignore")

# 1. Loading the metadata
path = # matadata path

try:
    df = pd.read_csv(path)
    df = df.drop_duplicates(keep='first')
    print("Dataframe loaded. Shape:", df.shape)
except:
    print("Check if metadata.csv is in the folder")

# 2. Basic Inspection
df.head()

# Statistical summary of numerical features
df.describe()

# Check types and missing values
df.info()

def unique_value(df):
    print("Unique values in dataframe")
    features = df.columns
    for feature in features:
        values = df[feature].unique()
        print(feature + ":", end=" ")
        for i in range(len(values) - 1):
            print(values[i], end="; ")
        print(values[-1])
        print()

unique_value(df)

# 3. Target Distribution
diagnostic_counts = df['diagnostic'].value_counts()
plt.figure(figsize=(8, 8))
plt.pie(diagnostic_counts, labels=diagnostic_counts.index, autopct='%1.1f%%', startangle=140)
plt.title("Distribution of Skin Lesion Diagnostics")
plt.legend(loc="best")
plt.show()

print("Raw Counts:\n", diagnostic_counts)

# 4. Categorizing Columns
# Identifying which are categorical for bar plots and which are numerical for correlation
cat_cols = ['gender', 'region', 'fitspatrick', 'smoke', 'drink', 'pesticide', 'itch', 'grew', 'bleed', 'changed']
num_cols = ['age', 'diameter_1', 'diameter_2']

# Plotting categorical features
def _bar_plot(df, feature):
    plt.figure(figsize=(10, 4))
    df[feature].value_counts().plot(kind='bar', color='skyblue')
    plt.title(f'Distribution of {feature}')
    plt.ylabel('Count')
    plt.xticks(rotation=45)
    plt.show()

for col in cat_cols:
    _bar_plot(df, col)

# 5. Relationship Testing
# Chi-Squared test

def chisquared_test(df: pd.DataFrame, col1: str, col2: str, alpha: float = 0.95):
    cross_table = pd.crosstab(df[col1], df[col2])
    val = stats.chi2_contingency(cross_table)
    chi2 = val[0]
    ddof = val[2]
    critical_value = stats.chi2.ppf(q=alpha, df=ddof)

    print(f'Testing relationship between {col1} and {col2}:')
    if chi2 >= critical_value:
        print(f'-> Reject H0: There is a significant relationship.')
    else:
        print(f'-> Retain H0: No significant relationship found.')
    print("----------------------------")

# Let's test a few clinical assumptions
for col in ['gender', 'smoke', 'itch', 'region']:
    chisquared_test(df, 'diagnostic', col)

# 6. Numerical Correlations
# Looking at how age and lesion size relate to each other
plt.figure(figsize=(10, 8))
corr = df[num_cols].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Matrix (Numerical Attributes)")
plt.show()